# Identificador único do projeto criado no SonarQube
sonar.projectKey=onboardly-v2

# Metadados opcionais
sonar.projectName=Onboardly v2
sonar.projectVersion=1.0

# Diretório contendo o código-fonte (padrão é o diretório atual ou src)
sonar.sources=frontend, backend

# Endereço do servidor SonarQube
sonar.host.url=http://localhost:9000